### PR TITLE
Keep Songcast tests from crashing

### PR DESCRIPTION
**Pull request by DoomHammer**
Both TestSongcast and TestSongcastCs were crashing due to uninitialised Library.

### CODE REVIEW

**Comment by DoomHammer** [comment]
Updated the code to compile on newer versions of GCC, ohNet and ohTopology.

**Comment by SimonChisholm** [comment]
Thanks.  I think I've applied all the changes, or close equivalents, now.  Let me know if anything is missing.

**Comment by DoomHammer** [comment]
Almost :) ohTopology build directory is still wrong and there is -lpthread instead of -pthread. Otherwise it looks great.

**Comment by SimonChisholm** [comment]
Thanks.  I've applied most of the makefile changes now.  I didn't change the ohTopology include directory - I think you can get the build to work using the current include path if you build ohTopology by calling ./waf build (are you currently using ./go ci-build ?).

I've updated ohSongcast's README to try and make it's build instructions clearer.

**Comment by DoomHammer** [comment]
That's how I was doing it. Thanks for clarification!

**Pull request closed without merging**
